server {
    listen       80;
    server_name  localhost;

    # Serve static React files
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy the API routes to the backend container
    location /demo/ {
        proxy_pass http://backend:8000/demo/;
    }
    location /protection/ {
        proxy_pass http://backend:8000/protection/;
    }
    location /mitigation/ {
        proxy_pass http://backend:8000/mitigation/;
    }
    location /health {
        proxy_pass http://backend:8000/health;
    }
    location /ws {
        proxy_pass http://backend:8000/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}
